/vis/open VRML2FILE
/vis/drawVolume

# This is the "Magic Sauce" for tracks
/tracking/storeTrajectory 1
/vis/scene/add/trajectories smooth
/vis/scene/endOfEventAction accumulate

# Color by charge (Protons Blue, Electrons Red)
/vis/modeling/trajectories/create/drawByCharge
/vis/modeling/trajectories/drawByCharge-0/set -1 red
/vis/modeling/trajectories/drawByCharge-0/set 1 blue

/vis/viewer/set/viewpointThetaPhi 90 0
/vis/viewer/flush